In [5]:
import numpy as np

In [6]:
a = np.random.randint(1,100,15)
a

array([96, 31, 41, 54, 15, 70, 33, 88, 39, 14, 29, 62, 15, 89, 61])

In [7]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[67, 11, 82, 48],
       [81, 14, 20, 80],
       [68, 39, 86, 76],
       [51, 32, 28, 28],
       [85, 40, 70, 59],
       [14, 22, 87, 25]])

### np.sort
returns a sorted copy or an array.

In [8]:
# 1D : Ascending Order 
np.sort(a) 

array([14, 15, 15, 29, 31, 33, 39, 41, 54, 61, 62, 70, 88, 89, 96])

In [9]:
# 1D : Descending Order 
np.sort(a)[::-1]

array([96, 89, 88, 70, 62, 61, 54, 41, 39, 33, 31, 29, 15, 15, 14])

In [10]:
# 2D : row-wise Ascending Order 
np.sort(b)

array([[11, 48, 67, 82],
       [14, 20, 80, 81],
       [39, 68, 76, 86],
       [28, 28, 32, 51],
       [40, 59, 70, 85],
       [14, 22, 25, 87]])

In [11]:
# 2D : row-wise Descending Order 
np.sort(b,axis=1)[::-1]
# Doesn't work , it just reverses the order of arrays

array([[14, 22, 25, 87],
       [40, 59, 70, 85],
       [28, 28, 32, 51],
       [39, 68, 76, 86],
       [14, 20, 80, 81],
       [11, 48, 67, 82]])

In [12]:
# 2D : column-wise Ascending Order 
np.sort(b,axis=0)

array([[14, 11, 20, 25],
       [51, 14, 28, 28],
       [67, 22, 70, 48],
       [68, 32, 82, 59],
       [81, 39, 86, 76],
       [85, 40, 87, 80]])

In [13]:
# 2D : column-wise Descending Order
np.sort(b,axis=0)[::-1]
# column wise descending order works just fine 

array([[85, 40, 87, 80],
       [81, 39, 86, 76],
       [68, 32, 82, 59],
       [67, 22, 70, 48],
       [51, 14, 28, 28],
       [14, 11, 20, 25]])

### np.append

In [14]:
a

array([96, 31, 41, 54, 15, 70, 33, 88, 39, 14, 29, 62, 15, 89, 61])

In [15]:
np.append(a,200)

array([ 96,  31,  41,  54,  15,  70,  33,  88,  39,  14,  29,  62,  15,
        89,  61, 200])

In [16]:
b

array([[67, 11, 82, 48],
       [81, 14, 20, 80],
       [68, 39, 86, 76],
       [51, 32, 28, 28],
       [85, 40, 70, 59],
       [14, 22, 87, 25]])

In [17]:
np.append(b,np.ones((b.shape[0],1)),axis=1)
# Alternatively, we can also use np.random instead of np.ones 

array([[67., 11., 82., 48.,  1.],
       [81., 14., 20., 80.,  1.],
       [68., 39., 86., 76.,  1.],
       [51., 32., 28., 28.,  1.],
       [85., 40., 70., 59.,  1.],
       [14., 22., 87., 25.,  1.]])

### np.concatenate
--> preferably used as a replacement of vstack and hstack

In [18]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c) 
print(d) 

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [19]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

In [21]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims
--> rarely used , but can come handy

In [22]:
print(a) 
print(a.shape) 

[96 31 41 54 15 70 33 88 39 14 29 62 15 89 61]
(15,)


In [23]:
temp = np.expand_dims(a,axis=0)
print(temp) 
print(temp.shape)

[[96 31 41 54 15 70 33 88 39 14 29 62 15 89 61]]
(1, 15)


In [24]:
temp = np.expand_dims(a,axis=1)
print(temp) 
print(temp.shape)

[[96]
 [31]
 [41]
 [54]
 [15]
 [70]
 [33]
 [88]
 [39]
 [14]
 [29]
 [62]
 [15]
 [89]
 [61]]
(15, 1)


### np.where

In [25]:
a

array([96, 31, 41, 54, 15, 70, 33, 88, 39, 14, 29, 62, 15, 89, 61])

In [26]:
# find all indices with values greater than 50
np.where(a>50)

(array([ 0,  3,  5,  7, 11, 13, 14], dtype=int64),)

In [27]:
# replace all values > 50 with 0 
np.where(a>50,0,a)

array([ 0, 31, 41,  0, 15,  0, 33,  0, 39, 14, 29,  0, 15,  0,  0])

In [28]:
# replace all even numbers with zero
np.where(a%2 == 0,0,a)

array([ 0, 31, 41,  0, 15,  0, 33,  0, 39,  0, 29,  0, 15, 89, 61])

In [29]:
# case study: replace all outliers with median 

### np.argmax

In [30]:
a

array([96, 31, 41, 54, 15, 70, 33, 88, 39, 14, 29, 62, 15, 89, 61])

In [31]:
# find the indices of the max element 
np.argmax(a)

0

In [32]:
np.max(a)

96

In [33]:
b
# However, argmax is generally used with 1D 

array([[67, 11, 82, 48],
       [81, 14, 20, 80],
       [68, 39, 86, 76],
       [51, 32, 28, 28],
       [85, 40, 70, 59],
       [14, 22, 87, 25]])

In [34]:
np.argmax(b)

22

In [35]:
np.argmax(b,axis=0)

array([4, 4, 5, 1], dtype=int64)

In [36]:
np.max(b,axis=0)

array([85, 40, 87, 80])

In [37]:
np.argmax(b,axis=1)

array([2, 0, 2, 0, 0, 2], dtype=int64)

In [38]:
np.max(b,axis=1)

array([82, 81, 86, 51, 85, 87])

### np.argmin

In [39]:
a

array([96, 31, 41, 54, 15, 70, 33, 88, 39, 14, 29, 62, 15, 89, 61])

In [40]:
np.argmin(a)

9

In [41]:
np.min(a)

14

In [42]:
b

array([[67, 11, 82, 48],
       [81, 14, 20, 80],
       [68, 39, 86, 76],
       [51, 32, 28, 28],
       [85, 40, 70, 59],
       [14, 22, 87, 25]])

In [43]:
np.argmin(b)

1

In [44]:
np.argmin(b,axis=0)

array([5, 0, 1, 5], dtype=int64)

In [45]:
np.argmin(b,axis=1)

array([1, 1, 1, 2, 1, 0], dtype=int64)

### np.cumsum 
--> cumulative sum 

In [46]:
a

array([96, 31, 41, 54, 15, 70, 33, 88, 39, 14, 29, 62, 15, 89, 61])

In [47]:
np.cumsum(a)

array([ 96, 127, 168, 222, 237, 307, 340, 428, 467, 481, 510, 572, 587,
       676, 737])

In [48]:
b 

array([[67, 11, 82, 48],
       [81, 14, 20, 80],
       [68, 39, 86, 76],
       [51, 32, 28, 28],
       [85, 40, 70, 59],
       [14, 22, 87, 25]])

In [49]:
np.cumsum(b)

array([  67,   78,  160,  208,  289,  303,  323,  403,  471,  510,  596,
        672,  723,  755,  783,  811,  896,  936, 1006, 1065, 1079, 1101,
       1188, 1213])

In [50]:
np.cumsum(b,axis=0)

array([[ 67,  11,  82,  48],
       [148,  25, 102, 128],
       [216,  64, 188, 204],
       [267,  96, 216, 232],
       [352, 136, 286, 291],
       [366, 158, 373, 316]])

In [51]:
np.cumsum(b,axis=1)

array([[ 67,  78, 160, 208],
       [ 81,  95, 115, 195],
       [ 68, 107, 193, 269],
       [ 51,  83, 111, 139],
       [ 85, 125, 195, 254],
       [ 14,  36, 123, 148]])

### np.cumprod
--> cumulative product

In [52]:
a

array([96, 31, 41, 54, 15, 70, 33, 88, 39, 14, 29, 62, 15, 89, 61])

In [53]:
np.cumprod(a)

array([         96,        2976,      122016,     6588864,    98832960,
       -1671627392,   670870912, -1092901888,   326499328,   276023296,
        -585259008, -1926320128,  1169969152,  1048039424,  -494104576])

In [54]:
b

array([[67, 11, 82, 48],
       [81, 14, 20, 80],
       [68, 39, 86, 76],
       [51, 32, 28, 28],
       [85, 40, 70, 59],
       [14, 22, 87, 25]])

In [55]:
np.cumprod(b)

array([         67,         737,       60434,     2900832,   234967392,
       -1005423808,  1366360320,  1934643200, -1588248576, -1812152320,
       -1226276864,  1292238848,  1479671808,   104857600, -1358954496,
         603979776,  -201326592,   536870912, -1073741824,  1073741824,
       -2147483648,           0,           0,           0])

In [56]:
np.cumprod(b,axis=0)

array([[         67,          11,          82,          48],
       [       5427,         154,        1640,        3840],
       [     369036,        6006,      141040,      291840],
       [   18820836,      192192,     3949120,     8171520],
       [ 1599771060,     7687680,   276438400,   482119680],
       [  921958360,   169128960, -1719662976,  -831909888]])

In [57]:
np.cumprod(b,axis=1)

array([[      67,      737,    60434,  2900832],
       [      81,     1134,    22680,  1814400],
       [      68,     2652,   228072, 17333472],
       [      51,     1632,    45696,  1279488],
       [      85,     3400,   238000, 14042000],
       [      14,      308,    26796,   669900]])

### np.percentile

In [58]:
a

array([96, 31, 41, 54, 15, 70, 33, 88, 39, 14, 29, 62, 15, 89, 61])

In [59]:
np.percentile(a,100)

96.0

In [60]:
np.percentile(a,0)

14.0

In [61]:
# median using np.percentile 
np.percentile(a,50)

41.0

In [62]:
# First Quartile using np.percnetile 
np.percentile(a,25)

30.0

In [63]:
# Third Quartile using np.percentile 
np.percentile(a,75)

66.0

In [64]:
np.median(a)

41.0

### np.histogram

In [65]:
a

array([96, 31, 41, 54, 15, 70, 33, 88, 39, 14, 29, 62, 15, 89, 61])

In [67]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 3, 1, 3, 1, 1, 2, 1, 2, 1], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [70]:
np.histogram(a,bins=[0,50,100])

(array([8, 7], dtype=int64), array([  0,  50, 100]))

### np.corrcoef

In [73]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

print(salary)
print(experience)

[20000 40000 25000 35000 60000]
[1 3 2 4 2]


In [74]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [ ]:
# Observing the results or np.corrcoef
# 1st Result : corrcoef(sal,sal) 
# 2nd Result : corrcoef(sal,exp) 
# 3rd Result : corrcoef(exp,sal) 
# 4th result : corrcoef(exp,exp) 
# so we get a matrix as a result 

### np.isin

In [75]:
a

array([96, 31, 41, 54, 15, 70, 33, 88, 39, 14, 29, 62, 15, 89, 61])

In [82]:
np.isin(a,41)

array([False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [83]:
items = [21,31,41,51,61]
np.isin(a,items)
# items --> elements
# a --> test elements
# returns : refer next cell 

array([False,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False,  True])

In [80]:
# help(np.isin) 
'''
Returns
    -------
    isin : ndarray, bool
        Has the same shape as `element`. The values `element[isin]`
        are in `test_elements`.
'''

'\nReturns\n    -------\n    isin : ndarray, bool\n        Has the same shape as `element`. The values `element[isin]`\n        are in `test_elements`.\n'

In [84]:
a[np.isin(a,items)]

array([31, 41, 61])

### np.flip

In [85]:
a

array([96, 31, 41, 54, 15, 70, 33, 88, 39, 14, 29, 62, 15, 89, 61])

In [86]:
np.flip(a)

array([61, 89, 15, 62, 29, 14, 39, 88, 33, 70, 15, 54, 41, 31, 96])

In [87]:
b

array([[67, 11, 82, 48],
       [81, 14, 20, 80],
       [68, 39, 86, 76],
       [51, 32, 28, 28],
       [85, 40, 70, 59],
       [14, 22, 87, 25]])

In [88]:
np.flip(b)
# flips row-wise as well as column-wise

array([[25, 87, 22, 14],
       [59, 70, 40, 85],
       [28, 28, 32, 51],
       [76, 86, 39, 68],
       [80, 20, 14, 81],
       [48, 82, 11, 67]])

In [89]:
# column-wise flipping 
np.flip(b,axis=0)

array([[14, 22, 87, 25],
       [85, 40, 70, 59],
       [51, 32, 28, 28],
       [68, 39, 86, 76],
       [81, 14, 20, 80],
       [67, 11, 82, 48]])

In [90]:
# row-wise flipping 

In [91]:
np.flip(b,axis=1)

array([[48, 82, 11, 67],
       [80, 20, 14, 81],
       [76, 86, 39, 68],
       [28, 28, 32, 51],
       [59, 70, 40, 85],
       [25, 87, 22, 14]])

### np.put

In [92]:
a

array([96, 31, 41, 54, 15, 70, 33, 88, 39, 14, 29, 62, 15, 89, 61])

In [93]:
np.put(a,[0,1],[110,530])

In [94]:
a

array([110, 530,  41,  54,  15,  70,  33,  88,  39,  14,  29,  62,  15,
        89,  61])

### np.delete

In [95]:
a

array([110, 530,  41,  54,  15,  70,  33,  88,  39,  14,  29,  62,  15,
        89,  61])

In [97]:
np.delete(a,0)

array([530,  41,  54,  15,  70,  33,  88,  39,  14,  29,  62,  15,  89,
        61])

In [98]:
np.delete(a,[0,2,4])

array([530,  54,  70,  33,  88,  39,  14,  29,  62,  15,  89,  61])

In [99]:
a

array([110, 530,  41,  54,  15,  70,  33,  88,  39,  14,  29,  62,  15,
        89,  61])

### set functions

In [101]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [102]:
# np.union1d
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [103]:
# np.intersect1d
np.intersect1d(m,n)

array([3, 4, 5])

In [104]:
# np.setdiff1d
np.setdiff1d(m,n)

array([1, 2])

In [105]:
np.setdiff1d(n,m)

array([6, 7])

In [106]:
# np.setxor1d --> union - intersection 
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [107]:
# np.in1d 
np.in1d(m,1)

array([ True, False, False, False, False])

In [109]:
np.in1d(m,10)

array([False, False, False, False, False])

In [110]:
m[np.in1d(m,1)]

array([1])

### np.clip

In [111]:
a

array([110, 530,  41,  54,  15,  70,  33,  88,  39,  14,  29,  62,  15,
        89,  61])

In [112]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 41, 54, 25, 70, 33, 75, 39, 25, 29, 62, 25, 75, 61])