# Creating Numpy Arrays

In [3]:
# !pip install numpy 

In [1]:
# importing numpy array
import numpy as np 

## np.array

In [32]:
# np.array
#1D --> Vector
a = np.array([1,2,3])     
print(a)
print(type(a))
print(a.ndim)

[1 2 3]
<class 'numpy.ndarray'>
1


In [33]:
# 2D --> Matrix 
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
2


In [34]:
# 3D --> Tensor
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(c.ndim)
print(c.dtype)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
int32


In [35]:
# dtype argument 
f = np.array([1,2,3,4],dtype=float)
print(f)
print(type(f))
# dtype property 
print(f.dtype)

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float64


In [36]:
f = np.array([1,2,3,4],dtype=bool)
print(f)
print(type(f))
print(f.dtype)

[ True  True  True  True]
<class 'numpy.ndarray'>
bool


In [63]:
np.array([1,2,3,4],dtype=str)

array(['1', '2', '3', '4'], dtype='<U1')

## np.arange

In [37]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [38]:
a = np.arange(1,11,2)
print(a)

[1 3 5 7 9]


In [42]:
# dtype argument 
np.arange(1,11,dtype=float)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [62]:
np.arange(1,11,dtype=str)

TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

## np.arange with reshape

In [49]:
# np.arange with reshape
a = np.arange(1,11).reshape(5,2)
print(a)
print(a.ndim)
print(a.size)
print(a[0].size)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2
10
2


In [48]:
a = np.arange(1,11).reshape(2,5)
print(a)
print(a.ndim)
print(a.size)
print(a[0].size) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
10
5


In [50]:
a = np.arange(1,11).reshape(5,5)
# the product of reshape fucntion arguments must match with the size of original array 

ValueError: cannot reshape array of size 10 into shape (5,5)

## np.ones

In [56]:
a = np.ones((3,4))
print(a)
print(a.dtype)
print(a.size)
print(a.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64
12
2


In [59]:
# dtype argument
a = np.ones((3,4),dtype=int)
print(a)
print(a.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int32


In [25]:
a = np.ones((3,4),dtype=str)
print(a)
print(a.dtype)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]
<U1


## np.zeros

In [65]:
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [66]:
# dtype
a = np.zeros((3,4),dtype=int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [67]:
a = np.zeros((3,4),dtype=str)
print(a)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


## np.random

In [3]:
np.random.random((3,4))

array([[0.37741288, 0.80561576, 0.35313412, 0.58586546],
       [0.61090571, 0.95897079, 0.84980312, 0.07385235],
       [0.15979422, 0.93981131, 0.3718731 , 0.1454118 ]])

## np.linspace

In [6]:
a = np.linspace(-10,10,20)
print(a)

[-10.          -8.94736842  -7.89473684  -6.84210526  -5.78947368
  -4.73684211  -3.68421053  -2.63157895  -1.57894737  -0.52631579
   0.52631579   1.57894737   2.63157895   3.68421053   4.73684211
   5.78947368   6.84210526   7.89473684   8.94736842  10.        ]


In [7]:
print(a[1] - a[0])

1.0526315789473681


In [8]:
print(a[2] - a[1])

1.0526315789473681


In [10]:
print(a[19] - a[18])

1.05263157894737


## np.identity

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Numpy Array Attributes

In [26]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

## ndim

In [27]:
print(a1.ndim)
print(a2.ndim) 
print(a3.ndim)

1
2
3


## shape 

In [28]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


## size

In [29]:
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


## itemsize

In [30]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
4


## dtype

In [31]:
print(a1.dtype)
print(a2.dtype)
print(a2.dtype)

int32
float64
float64


# Changing Datatype --> astype

In [35]:
a3.dtype

dtype('int32')

In [36]:
a3.astype(np.int16)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int16)

# Array Operations

In [38]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [39]:
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [40]:
print(a2)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## scalar operations

### arithmetic 

In [44]:
a1 * 2
# matrix * scalar 

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [45]:
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### relational 

In [48]:
a1 < 5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [49]:
a1 == 5

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

## vector operations

### arithmetic

In [50]:
a1 + a2 

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [51]:
a1 - a2 

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [52]:
a1 * a2 

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# Array Fucntions